# Generated by Django 4.2.7 on 2026-02-20

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email address")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="t\u00e9l\u00e9phone")),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="avatars/", verbose_name="avatar")),
                ("date_of_birth", models.DateField(blank=True, null=True, verbose_name="date de naissance")),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "F\u00e9minin"), ("O", "Autre")],
                        max_length=1,
                        verbose_name="genre",
                    ),
                ),
                ("height", models.FloatField(blank=True, null=True, verbose_name="taille (cm)")),
                ("weight", models.FloatField(blank=True, null=True, verbose_name="poids (kg)")),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="ville")),
                ("country", models.CharField(blank=True, default="S\u00e9n\u00e9gal", max_length=100, verbose_name="pays")),
                ("dietary_preferences", models.JSONField(blank=True, default=list, verbose_name="pr\u00e9f\u00e9rences alimentaires")),
                ("allergies", models.JSONField(blank=True, default=list, verbose_name="allergies")),
                ("is_premium", models.BooleanField(default=False, verbose_name="premium")),
                ("premium_expiry", models.DateTimeField(blank=True, null=True, verbose_name="expiration premium")),
                ("share_with_doctor", models.BooleanField(default=False, verbose_name="partager avec m\u00e9decin")),
                ("doctor_name", models.CharField(blank=True, max_length=200, verbose_name="nom du m\u00e9decin")),
                ("participate_in_research", models.BooleanField(default=False, verbose_name="participer \u00e0 la recherche")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="cr\u00e9\u00e9 le")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="mis \u00e0 jour le")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                ("message", models.TextField(verbose_name="message")),
                ("activity_type", models.CharField(default="general", max_length=50, verbose_name="type")),
                ("is_read", models.BooleanField(default=False, verbose_name="lu")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="cr\u00e9\u00e9 le")),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="users.user"),
                ),
            ],
            options={
                "verbose_name": "Activit\u00e9 utilisateur",
                "verbose_name_plural": "Activit\u00e9s utilisateurs",
                "ordering": ["-created_at"],
            },
        ),
    ]
