release: python manage.py makemigrations --noinput && python manage.py migrate --noinput --run-syncdb && python manage.py collectstatic --noinput
web: python manage.py makemigrations --noinput && python manage.py migrate --noinput --run-syncdb && python manage.py collectstatic --noinput && gunicorn biomex.wsgi:application
